# Generated by Django 5.1.2 on 2025-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingschedule',
            name='department',
            field=models.TextField(choices=[('Main', 'Main'), ('CEIT', 'Computing and Information Technology'), ('CTE', 'Civil and Environmental Engineering'), ('CAS', 'Applied Sciences'), ('COT', 'Technology'), ('COHES', 'Health Sciences'), ('COB', 'Business and Economics'), ('COE', 'Engineering'), ('COED', 'Education'), ('COL', 'Law'), ('COA', 'Agriculture'), ('COH', 'Humanities and Social Sciences')], null=True),
        ),
    ]
